name: Action triggered on push
run-name: ${{ github.actor }} is learning GitHub Actions
on: [workflow_dispatch]

jobs:
  install_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update
      - run: sudo apt install python3
      - run: python3 -c "print('Code executed by python')"
      - run: echo "some stuff"

